sudo: false

os:
  - linux

language: generic

env:
- PY=2.7
- PY=3.6

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test

before_install:
- if [ "$PY" = "2.7" ];  then wget "https://repo.continuum.io/miniconda/Miniconda2-latest-$OS-x86_64.sh" -O miniconda.sh; fi
- if [ "$PY" = "3.6" ];  then wget "https://repo.continuum.io/miniconda/Miniconda3-latest-$OS-x86_64.sh" -O miniconda.sh; fi
- chmod +x miniconda.sh
- if [ "$OS" = "Linux" ]; then
    ./miniconda.sh -b  -p /home/travis/miniconda;
  fi
- PATHPREFIX=$(if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then echo "/Users/travis/miniconda/bin"; else echo "/home/travis/miniconda/bin"; fi)
- export PATH=$PATHPREFIX:$PATH

install:
- conda install --yes python=$PY numpy scipy nose $HDF5 sphinx==1.3.1 mock swig
- pip install coverage
- pip install coveralls
- pip install git+git://github.com/OpenMDAO/OpenMDAO.git

script:
- pip install -e .
- testflo . --coverage --coverpkg openaerostruct

after_success:
- coveralls
