sudo: false

os:
  - linux

language: generic

env:
- FORTRAN= PY=2.7
- FORTRAN= PY=3.6
- FORTRAN=1 PY=2.7

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gfortran
    - libblas-dev
    - liblapack-dev
    - libopenmpi-dev
    - openmpi-bin

before_install:
- OS=$(if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then echo "MacOSX"; else echo "Linux"; fi)
- if [ "$OS" = "MacOSX" ] && [ "$MPI" ]; then brew install openmpi; fi
- if [ "$PY" = "2.7" ];  then wget "https://repo.continuum.io/miniconda/Miniconda2-latest-$OS-x86_64.sh" -O miniconda.sh; fi
- if [ "$PY" = "3.4" ];  then wget "https://repo.continuum.io/miniconda/Miniconda3-latest-$OS-x86_64.sh" -O miniconda.sh; fi
- chmod +x miniconda.sh
- if [ "$OS" = "Linux" ]; then
    ./miniconda.sh -b  -p /home/travis/miniconda;
  fi
- if [ "$OS" = "MacOSX" ]; then
    ./miniconda.sh -b  -p /Users/travis/miniconda;
  fi
- PATHPREFIX=$(if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then echo "/Users/travis/miniconda/bin"; else echo "/home/travis/miniconda/bin"; fi)
- export PATH=$PATHPREFIX:$PATH

install:
- conda install --yes python=$PY numpy scipy nose $HDF5 sphinx==1.3.1 mock swig
- if [ "$OS" = "Linux" ]; then
    if [ "$PY" = "2.7" ]; then
        pip install https://openmdao.org/dists/pyoptsparse-1.0.0-cp27-none-linux_x86_64.whl;
    elif [ "$PY" = "3.4" ]; then
        pip install https://openmdao.org/dists/pyoptsparse-1.0.0-py3-none-linux_x86_64.whl;
    fi
  fi
- pip install coverage
- pip install coveralls
- pip install git+git://github.com/OpenMDAO/openmdao.git

script:
- if [ "$FORTRAN" ]; then
    cd openaerostruct/fortran; make; cd ../..;
  fi
- cd ..
- export PYTHONPATH=$PYTHONPATH:$PWD
- cd -
- testflo . --coverage --coverpkg openaerostruct

after_success:
- coveralls

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: wingbox